language: python
python:
 - "3.5"

# command to run tests
script:
 - coverage run -m unittest HW02TestTriangle HW05FS HW05FS_test

install:
 - pip install coverage
 
after_success:
 - bash <(curl -s https://codecov.io/bash)
