language: python
python:
 - "3.5"

# command to run tests
script:
 - python -m unittest HW02TestTriangle
 - coverage run -m unittest HW05FS_test
install:
 - pip install coverage
 
 after_success:
  - codecov
