language: python
python:
 - "3.5"

# command to run tests
script:
 - python -m unittest HW02TestTriangle
 - coverage run -m unittest discover
install:
 - pip install coverage
 
after_success:
 - bash <(curl -s https://codecov.io/bash)
